version: "3.9"

services:
  backend:
    build: ./backend
    container_name: job-app-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: job-app-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: job-app-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobapp
    ports:
      - "5432:5432"
